# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JsonToModelOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JsonToModelOC
 #pod版本 1.8.4
 pod 'MJExtension'
 pod 'JSONModel'
 pod 'YYModel'

end
